#include "../src/burn/drv/snes/d_snes.cpp"
#include "../src/burn/drv/snes/snes_65816.cpp"
#include "../src/burn/drv/snes/snes_io.cpp"
#include "../src/burn/drv/snes/snes_main.cpp"
#include "../src/burn/drv/snes/snes_ppu.cpp"
#include "../src/burn/drv/snes/snes_spc700.cpp"
